"""add customers.kyc_status (nullable)

Revision ID: 20b73cd35c99
Revises: 2953b37195b3
Create Date: 2026-09-14 14:52:55.752392

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '20b73cd35c99'
down_revision = '2953b37195b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('kyc_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'kyc_status')
    # ### end Alembic commands ###
