"""add customer_duplicate_candidates table

Revision ID: 2953b37195b3
Revises: d463a6468670
Create Date: 2026-09-14 14:49:51.223338

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2953b37195b3'
down_revision = 'd463a6468670'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_duplicate_candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_id_a', sa.Uuid(), nullable=False),
    sa.Column('customer_id_b', sa.Uuid(), nullable=False),
    sa.Column('match_probability', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    # Deliberately no ForeignKeyConstraint on customer_id_a/customer_id_b:
    # a "merged" resolution deletes the loser Customer row, and this table
    # is meant to survive as a permanent audit trail of that decision.
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'customer_id_a', 'customer_id_b', name='uq_dup_candidate_tenant_pair')
    )
    op.create_index(op.f('ix_customer_duplicate_candidates_tenant_id'), 'customer_duplicate_candidates', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_duplicate_candidates_tenant_id'), table_name='customer_duplicate_candidates')
    op.drop_table('customer_duplicate_candidates')
    # ### end Alembic commands ###
