"""initial canonical schema

Revision ID: 743aec8b5570
Revises: 
Create Date: 2026-09-13 03:49:14.265029

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '743aec8b5570'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_tenant_id'), 'sources', ['tenant_id'], unique=False)
    op.create_table('mapping_specs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('spec_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('parent_version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mapping_specs_tenant_id'), 'mapping_specs', ['tenant_id'], unique=False)
    op.create_table('onboarding_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mapping_spec_version', sa.Integer(), nullable=True),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encoding', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('delimiter', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_id', 'file_hash', name='uq_batch_tenant_source_filehash')
    )
    op.create_index(op.f('ix_onboarding_batches_file_hash'), 'onboarding_batches', ['file_hash'], unique=False)
    op.create_index(op.f('ix_onboarding_batches_tenant_id'), 'onboarding_batches', ['tenant_id'], unique=False)
    op.create_table('column_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('column_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profile_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['onboarding_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_column_profiles_batch_id'), 'column_profiles', ['batch_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('natural_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('legal_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('risk_tier', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vat_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_batch_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['source_batch_id'], ['onboarding_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'natural_key', name='uq_customers_tenant_naturalkey')
    )
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_table('mapping_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mapping_spec_id', sa.Uuid(), nullable=False),
    sa.Column('column_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('proposed', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chosen', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('decided_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mapping_spec_id'], ['mapping_specs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mapping_reviews_mapping_spec_id'), 'mapping_reviews', ['mapping_spec_id'], unique=False)
    op.create_table('quarantine',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('raw_record_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_codes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('suggested_fix', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['onboarding_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quarantine_batch_id'), 'quarantine', ['batch_id'], unique=False)
    op.create_index(op.f('ix_quarantine_tenant_id'), 'quarantine', ['tenant_id'], unique=False)
    op.create_table('raw_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['onboarding_batches.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_records_batch_id'), 'raw_records', ['batch_id'], unique=False)
    op.create_index(op.f('ix_raw_records_tenant_id'), 'raw_records', ['tenant_id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('opened_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_tenant_id'), 'accounts', ['tenant_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('natural_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('ticket_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('opened_at', sa.Date(), nullable=True),
    sa.Column('closed_at', sa.Date(), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_batch_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['source_batch_id'], ['onboarding_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'natural_key', name='uq_tickets_tenant_naturalkey')
    )
    op.create_index(op.f('ix_support_tickets_tenant_id'), 'support_tickets', ['tenant_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('natural_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('invoice_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount_minor_units', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tax_amount_minor_units', sa.Integer(), nullable=True),
    sa.Column('po_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_batch_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['source_batch_id'], ['onboarding_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'natural_key', name='uq_invoices_tenant_naturalkey')
    )
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_support_tickets_tenant_id'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_accounts_tenant_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_raw_records_tenant_id'), table_name='raw_records')
    op.drop_index(op.f('ix_raw_records_batch_id'), table_name='raw_records')
    op.drop_table('raw_records')
    op.drop_index(op.f('ix_quarantine_tenant_id'), table_name='quarantine')
    op.drop_index(op.f('ix_quarantine_batch_id'), table_name='quarantine')
    op.drop_table('quarantine')
    op.drop_index(op.f('ix_mapping_reviews_mapping_spec_id'), table_name='mapping_reviews')
    op.drop_table('mapping_reviews')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_column_profiles_batch_id'), table_name='column_profiles')
    op.drop_table('column_profiles')
    op.drop_index(op.f('ix_onboarding_batches_tenant_id'), table_name='onboarding_batches')
    op.drop_index(op.f('ix_onboarding_batches_file_hash'), table_name='onboarding_batches')
    op.drop_table('onboarding_batches')
    op.drop_index(op.f('ix_mapping_specs_tenant_id'), table_name='mapping_specs')
    op.drop_table('mapping_specs')
    op.drop_index(op.f('ix_sources_tenant_id'), table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
